{
 "title": "on-cpu 调度延迟",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "process_name",
    "query": "SELECT DISTINCT comm \nFROM shepherd.sched_latency \nWHERE is_preempt = 1 \nORDER BY comm"
   }
  ]
 },
 "panels": [
  {
   "title": "抢占总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "抢占进程",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "irate(sched_preempte[5m])", "legendFormat": "{{comm}}-{{pid}}" }
     ]
    },
    {
     "title": "被抢占进程",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "irate(sched_preempted[5m])", "legendFormat": "{{comm}}-{{pid}}" }
     ]
    },
    {
     "title": "调度延迟",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum by (pid,comm) (irate (sched_latencies[5m])) ",
       "legendFormat": "{{pid}}-{{comm}}"
      }
     ]
    }
   ]
  },
  { "title": "抢占详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "process_name" },
  {
   "title": "抢占拓扑",
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "-- Nodes 查询：筛选 nfs-trace 相关的节点\nSELECT \n    preempted_comm as id,\n    preempted_comm as title,\n    count(DISTINCT comm) as mainstat\nFROM sched_latency\nWHERE is_preempt = 1\n    AND ($__timeFilter(datetime)) \n    AND (preempted_comm = '$process_name' OR comm = '$process_name')  -- 筛选条件\nGROUP BY preempted_comm\n\nUNION DISTINCT\n\nSELECT \n    comm as id,\n    comm as title,\n    count(DISTINCT preempted_comm) as mainstat\nFROM sched_latency\nWHERE is_preempt = 1\n    AND ($__timeFilter(datetime))\n    AND (preempted_comm = '$process_name' OR comm = '$process_name')  -- 筛选条件\nGROUP BY comm;"
    },
    {
     "rawSql": "-- Edges 查询 nfs-trace 相关的边\nSELECT \n    concat(comm, '--', preempted_comm) as id,\n    comm as source,\n    preempted_comm as target,\n    count(*) as mainstat,\n    concat(count(*), ' times') as subtitle     \nFROM sched_latency\nWHERE is_preempt = 1\n    AND ($__timeFilter(datetime)) \n    AND preempted_comm != comm\n    AND (comm = '$process_name' OR preempted_comm = '$process_name')  -- 筛选nfs-trace相关的记录\nGROUP BY comm, preempted_comm\nORDER BY mainstat DESC;"
    }
   ]
  },
  {
   "title": "抢占明细",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "rawSql": "-- Edges 查询 nfs-trace 相关的边\nSELECT \n    concat(comm, '--', preempted_comm) as id,\n    comm as source,\n    preempted_comm as target,\n    pid as preempt_pid,\n    tid as preempt_tid,\n    preempted_pid,\n    datetime\nFROM sched_latency\nWHERE is_preempt = 1\n\tAND ($__timeFilter(datetime))\n    AND (comm = '$process_name' OR preempted_comm = '$process_name') --过滤服务名称\nORDER BY datetime DESC;"
    }
   ]
  }
 ]
}