pprof:
  enable: true

btf:
  kernel: "/sys/kernel/btf/vmlinux"

output:
  type: file
  clickhouse:
    host: "192.168.200.201"
    port: "9000"
    username: "default"
    password: "jjkcs123"
    database: "shepherd"
